services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lY7YTq646zZe
    ports:
      - '5432:5432'
    volumes:
      - ./nestdb-postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
